spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s


app:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs/product-service
        name: Product Service API
      - url: /v3/api-docs/order-service
        name: Order Service API
      - url: /v3/api-docs/user-service
        name: User Service API
      - url: /v3/api-docs/auth-service
        name: Auth Service API
      - url: /v3/api-docs/cart-service
        name: Cart Service API

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "api-gateway"
    description: "Kasyus Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      kasyus:
        apigateway: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOSTNAME:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/

server:
  port: 8072

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


