spring:
  application:
    name: message

  cloud:
    function:
      definition: email|sms

    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
server:
  port: 9010

info:
  app:
    name: "message"
    description: "Kasyus Message Service Application"
    version: "1.0.0"

logging:
  level:
    com:
      kasyus:
        message: DEBUG