spring:
  application:
    name: message

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


server:
  port: 8089

info:
  app:
    name: "message"
    description: "Kasyus Message Service Application"
    version: "1.0.0"

logging:
  level:
    com:
      kasyus:
        message: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"