spring:
  application:
    name: "product-service"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kasyus_products}
    username: ${SPRING_DATASOURCE_USERNAME:kasyus}
    password: ${SPRING_DATASOURCE_PASSWORD:kasyus123}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: "product-service"
    description: "Kasyus Product Service Application"
    version: "1.0.0"

logging:
  level:
    com:
      kasyus:
        product-service: DEBUG
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOSTNAME:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
server:
  port: 8081