apiVersion: v1
kind: ConfigMap
metadata:
  name: kasyus-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  EUREKA_APPLICATION_NAME: "discovery-service"
  DISCOVERY_SERVICE_HOSTNAME: "discovery-service"
  DISCOVERY_SERVICE_PORT: "8761"

  GATEWAY_APPLICATION_NAME: "api-gateway"
  AUTH_SERVICE_HOSTNAME: "auth-service"
  USER_SERVICE_HOSTNAME: "user-service"
  PRODUCT_APPLICATION_NAME: "product-service"
  CART_APPLICATION_NAME: "cart-service"
  ORDER_APPLICATION_NAME: "order-service"

  SPRING_REDIS_HOST: "redis"
  OTEL_SERVICE_NAME: "kasyus"
  MESSAGE_APPLICATION_NAME: "message-service"
