apiVersion: v1
kind: ConfigMap
metadata:
  name: kasyus-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  EUREKA_APPLICATION_NAME: "discovery-service"
  PRODUCT_APPLICATION_NAME: "product-service"
  ORDER_APPLICATION_NAME: "order-service"
  GATEWAY_APPLICATION_NAME: "api-gateway"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  DISCOVERY_SERVICE_HOSTNAME: "discovery-service"
  SPRING_REDIS_HOST: "redis"
  OTEL_SERVICE_NAME: "kasyus"
  MESSAGE_APPLICATION_NAME: "message-service"
  DISCOVERY_SERVICE_PORT: "8761"
