apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  labels:
    app: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.5.1
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy/config.alloy
              subPath: config.alloy
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

---
apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  selector:
    app: alloy
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    server:
      http_listen_port: 12345
    storage:
      path: /var/lib/alloy/data 