apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deployment
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: kasyus-prod-discovery-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: kasyus-configmap
              key: EUREKA_APPLICATION_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
