apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-read
  labels:
    app: loki-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-read
  template:
    metadata:
      labels:
        app: loki-read
    spec:
      containers:
        - name: loki-read
          image: grafana/loki:3.1.2
          args:
            - "-config.file=/etc/loki/config.yaml"
            - "-target=read"
          ports:
            - containerPort: 3100
            - containerPort: 7946
            - containerPort: 9095
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/config.yaml
              subPath: config.yaml
      volumes:
        - name: loki-config
          configMap:
            name: loki-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-write
  labels:
    app: loki-write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-write
  template:
    metadata:
      labels:
        app: loki-write
    spec:
      containers:
        - name: loki-write
          image: grafana/loki:3.1.2
          args:
            - "-config.file=/etc/loki/config.yaml"
            - "-target=write"
          ports:
            - containerPort: 3100
            - containerPort: 7946
            - containerPort: 9095
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/config.yaml
              subPath: config.yaml
      volumes:
        - name: loki-config
          configMap:
            name: loki-config

---
apiVersion: v1
kind: Service
metadata:
  name: loki-read
spec:
  selector:
    app: loki-read
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095

---
apiVersion: v1
kind: Service
metadata:
  name: loki-write
spec:
  selector:
    app: loki-write
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h 